### ISSUE TITLE
Health status should be propagated to Eureka / custom healthcheck handlers

### ISSUE THREAD

**Issue by fjvieira** [jquatier/eureka-js-client#112]
Hello,

I am facing a issue now because of the following case:

The heartbeat does not change the status that is registered in Eureka.

So, for some reason the application /health endpoint returns down, in Eureka is still UP. 

The heartbeat should consider the current health indicator.

**Comment by jquatier** [comment]
Hey @fjvieira,
The Eureka server's status of an application is only determined based off heartbeats, it does not call the healthcheck URL. In a typical Netflix OSS stack the healthcheck URL callback is really only used by Asgard and ELBs to determine if the instance is ready to receive traffic. It's an optional field. This is documented [here](https://github.com/Netflix/asgard/wiki/Eureka-Integration) and [here](https://github.com/Netflix/eureka/wiki/Integrating-Eureka-and-Asgard) if you need more detail. It's also been discussed a bit [here](https://groups.google.com/d/msg/eureka_netflix/ULvUqYIa_qA/lxeAaTyOeNkJ) with some of the authors. 

In any case, similar to the Java Eureka client, the `eureka-js-client` module is only in charge of registering and sending heartbeats. It advertises the `healthcheckUrl` to the Eureka server as a callback for other applications to use. Hope this helps!

**Comment by fjvieira** [comment]
@jquatier 

Hello, initally I understood the same you described. We am using Eureka + Spinnaker to run the CD process and the behavior is somewhat similar (Asgard). 
The Eureka documentation from Netflix was implemented AS-IS, i.e. as described [here](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations). 
Note that in the **Take instance out of service** action, you can change the status using a parameter.
The problem is that if an instance is DOWN because of some health check issue (DB, resources, etc) after startup, it should not be UP in Eureka. An application that is not healthy should not be the destination of requests anyway.
As we have here Java and Node.js instances, I know the behavior of what Spring Cloud team implemented. 
If you check[EurekaHealthCheckHandler.java](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaHealthCheckHandler.java), you will see that it creates a list of all health checks to take into account in the application status and it will determine the status send to Eureka in the heartbeat. 

It is exactly what I override of your client + a way of providing the health status to determine the instance status in Eureka.

**Comment by jquatier** [comment]
@fjvieira Thanks for the further details. I misunderstood you because I thought you wanted the Eureka server to call the `healthcheckUrl`. On reading Spring Cloud's implementation I think we could implement something similar. Here's what I'm thinking, let me know your thoughts:

To keep things flexible we could add an optional callback to the configuration `healthcheckHandler` that is invoked on every heartbeat. That function could return true or false if the instance is healthy and it's up to your application to implement that function however you desire and return a boolean accordingly. If the function returns false we would not send a heartbeat and possibly also set the instance status to `DOWN`. If the function returns true we execute the heartbeat normally. Do you think that would work for your needs? In side that function you can perform a database check or other logic, it's entirely up to you.

Thanks for the idea and would be great to get your thoughts!

**Comment by fjvieira** [comment]
@jquatier Hello. I like the callback idea. 
Regarding the heartbeat, the application still needs send it, because after send the status, the heartbeat will indicate that instance is running (besides the unhealthy or out of service status). 
Spinnaker and other tools that implement Red/Black deployment use the out of service status in that process, so we must take care of it. 

As a workaround, By now I am just changing this.config.instance.status in EurekaClient.js after read my global health status and setting a uri: `${this.config.instance.app}/${this.instanceId}/status?value=${this.config.instance.status}` in the renew overridden method.
It works, but the out of service behavior needs further tests.

I am glad to contribute to it.

**Comment by jquatier** [comment]
@fjvieira I think we are actually talking about two different things. The OUT_OF_SERVICE status is usually only be set from management consoles like spinnaker or asgard as a facility to do red/black deploys (specifically to direct [traffic flow](https://github.com/Netflix/eureka/wiki/Understanding-eureka-client-server-communication#about-instance-statuses)). The application itself is usually only responsible for reporting UP or DOWN ([more info](https://groups.google.com/d/msg/eureka_netflix/ULvUqYIa_qA/-_AxuBg8NlQJ)) based off heartbeats. This is important in your example because we don't want the client to overwrite the status after Spinnaker sets it (as you said). Usually the flow is something like:

1. Management UI sets instance status to `OUT_OF_SERVICE` to prevent traffic, this sets the overriddenStatus in Eureka.
2. Instance continues to send heartbeats on interval letting the UI know it's `UP` or `DOWN`
3. Management UI removes `OUT_OF_SERVICE` status, traffic flows to instances.

Even if the instance re-registers, it never changes to UP unless the `OUT_OF_SERVICE` status is removed.

I don't think we would want to change the `renew()` method to set the status because that's no longer hitting the heartbeat URI; it's an overridden status change. The heartbeat URI is always what should be used so that the Eureka server can determine when to _automatically_ take the instance out of it's registry if it hasn't reported in several minutes. It doesn't take a status and is just an empty [PUT request](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations). You can see this happen if you kill your instance and watch it fall out of the list in Eureka.

Anyway, what I was describing about above was a way to implement custom heartbeat logic so that you could perform a database or dependency check with every heartbeat prior to sending it. We can also optionally set the status to `DOWN` if we don't want to wait for the instance to fall out of the registry due to lack of heartbeats, but I don't think we should use `OUT_OF_SERVICE` on the application side.

**Comment by fjvieira** [comment]
@jquatier Hello, Jacob. No, we are talking about the same behavior. 
You are completely right about OUT_OF_SERVICE status. What I tried to mean is that after some tests I found the following problem:
- I acted on behalf of Spinnaker, setting the status to OUT_OF_SERVICE. The status of instance automatically turns to OUT_OF_SERVICE and Eureka serves this in the register;
- The application will receive its own status in the register refresh request (that is cached);
- Meanwhile, If the application health check turns to DOWN and the cache is still indicating UP (i.e. it was not refreshed in order to have the current remote status), **the application will send status DOWN and it will overwrite the current status in Eureka (OUT_OF_SERVICE)**.

So, my concern is that this mechanism can fail during Red/Black deployments.

Talking about your idea, I think the concept is completely right. My only concern is related to sync of status and actions.

**Comment by fjvieira** [comment]
Going further, 

I was debbuging Eureka server and client (java). 

I noticed that the heartbeat PUT request was

/eureka/apps/appID/instanceID?status=UP&lastDirtyTimestamp=1490691499240

Investigating this lastDirtyTimestamp parameter, you can read [here](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/resources/InstanceResource.java) the following: 
> last timestamp when this instance information was updated.

So I guess it will be necessary to deal with it in order to have the right behavior.

**Comment by jquatier** [comment]
@fjvieira Thanks for the additional detail. Hope I'm not misunderstanding anything. A few more clarifications:

> Meanwhile, If the application health check turns to DOWN and the cache is still indicating UP (i.e. it was not refreshed in order to have the current remote status), the application will send status DOWN and it will overwrite the current status in Eureka (OUT_OF_SERVICE).

I understand the problem, but this scenario would only happen if you were calling the "Take instance out of service" REST endpoint (`instanceId/status?value=DOWN`), which you did say above you modified your application to call by overriding the `renew()` method and adding it to the instance config object. Like I said, in the normal scenario the application shouldn't call that endpoint and that's why this module doesn't do that. Normal instance heartbeats that call the heartbeat PUT endpoint, which is what this module calls, will not alter the status set via Spinnaker. It will still remain OUT_OF_SERVICE until that status is removed. I tested this out today with a local Eureka server just to make sure.

The PUT endpoint you found does have a `status` parameter but you'll notice it's not used. Only the `overriddenStatus` parameter is used if it's a replication from another node. Anyway, this module is already being used with this type of red/black deployment without any issues. If an instance goes down, we assume either the application will stop reporting heartbeats, or it's `healthcheckURL` will fail. The callback idea could enhance that by letting users implement custom heartbeat logic, but I don't think we need to change the heartbeat URL.

**Comment by fjvieira** [comment]
@jquatier Hello. 
I think now I understood your point. 

Java clients request looks like it:
PUT .../eureka/apps/appID/instanceID?status=UP&lastDirtyTimestamp=1490691499240
And Spinnaker request looks like it
PUT .../eureka/apps/appID/instanceID/status?value=OUT_OF_SERVICE (OR UP)

Analyzing and debugging the behavior of implementations in Java (client and [server](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/resources/InstanceResource.java)), I realized that those parameters using in the PUT request are only considered in case of replication. The  PUT request in ../status is only used in administrative actions take outside of the client. These means that you can send whatever you want in the renew request (status and overriddenStatus) without even affect the current status in the register (I tried it and the status was still UP).

So far, it is not what I want to achieve: to indicate to the clients that a service is DOWN and there is no reason to send requests against it.

**Comment by jquatier** [comment]
@fjvieira Yeah those 2 endpoints are confusing because they look very similar. 

Keep in mind that clients cache the registry and may not have the most up-to-date picture of the world when they make the request. Even if you were able to update the registry to let clients know if the service was DOWN, they would likely not know about it until the next refresh of their cache. Requests would still go to the DOWN service for a period of time.

If you're using Eureka service discovery, and especially Spring Cloud, it's usually assumed that you will also use a fault tolerant and resilient HTTP strategy like [Ribbon](https://www.youtube.com/watch?v=apD7Ovl85vE&t=35:30). In this setup, it doesn't really matter if the client sends a request to a DOWN service because it's going to retry anyway on failure or timeout. When it retries, it will go to the next available instance. You MUST have this logic because it's always possible the clients cache of the registry has an instance that is cached as UP but has really gone DOWN in the last minute or so.

Anyway, I see what you are trying to accomplish, but really if all the pieces of a fault tolerant architecture are in place, it shouldn't be necessary, in my opinion. This type of setup has well-documented success on large production websites. Services go up and down all the time but the overall infrastructure can handle these faults via retries, software load balancing, and circuit breakers.

**Comment by nocturnalme** [comment]
@jquatier Exactly.

The client has load balancing (round robin as default one) and a circuit breaker (based on IP, if my memory is correct). This is the reason Netflix does not care about it.
So, if you plan to use another technology, you must ship those features in your software. 
I developed the load balancing feature to JS and it will be necessary to implement/adopt a circuit breaker+ some retry strategy.
Anyway, thank you.

**Comment by jquatier** [comment]
@nocturnalme If you're looking for a circuit breaker I highly recommend [Brakes](https://github.com/awolden/brakes). Good luck with the project!
