### ISSUE TITLE
Getting list of all apps and their instances in a List

### ISSUE THREAD

**Issue by pmascheroni** [jquatier/eureka-js-client#122]
Spring Could Eureka client configuration already has two functions, getInstancesByAppId() and getInstancesByVipAddress() which allow for access to individual instances of apps/microservices.  The ability to access all apps and their instances is not integrated, however this would make it easy to search for specific apps if the VipAddress or AppId is not know.  

For organization and fast access/searching of apps having a full list would allow for individual searches and sorting of specific features desired by clients.  This would allow for the possibility of building an personalized micro-service registry instead of the default spring based eureka page.

Is there a way to add a function much like the two getInstances* applications which would return an array of all the apps and all of their instances.   I will be happy to work on this and issue a pull request

**Comment by shaileshfsr** [comment]
This will be a very helpful feature for us since we want to show a list of all micro services registered with Eureka to generate some useful developer facing documentation

**Comment by jquatier** [comment]
My apologies for the delay on this. I understand the need, it sounds like an interesting project. Since you just want the complete registry in a list, it might just be easiest to call the Eureka REST service directly i.e. `<SERVER_HOST_PORT>/apps` (the same service this client calls). That will return everything all in one shot as JSON and you can sort/filter from there. If you don't want to do that, we store the cached registry under a `cache` variable on the client that you could also access if needed.
