### ISSUE TITLE
How do I know the microservice is closed？

### ISSUE THREAD

**Issue by Janking** [jquatier/eureka-js-client#124]
I had multiple microservices, when I registered successfully, 

`instance.length > 1` and I choose one of the instances randomly

`const instances = client.getInstancesByAppId('YOURSERVICE');`

if I shutdown one of the microservice,how to detect it immediately ?

**Comment by jquatier** [comment]
Hey @Janking, 

If you shut down the service, it will stop sending heartbeats to the Eureka server and eventually fall out of the registry. Both the Java client and this Eureka client cache the registry for a configurable amount of time, so it's always possible you will send a request to an instance that has gone down. In addition to that, the Eureka server won't drop it out of the registry until several heartbeats have been missed. 

If you're using Eureka service discovery, the normal pattern is that you also use a fault tolerant and resilient HTTP strategy like Ribbon. In this setup, it doesn't really matter if the client sends a request to a DOWN service, because it's going to retry anyway on failure or timeout. When it retries, it will go to the next available instance. You must have this logic due to the nature of instances going up and down. 

Hope this helps!

**Comment by Janking** [comment]
@jquatier  Thanks , but I don't know how to use Robbin in node project ,  can you provide any examples ? ☹️

**Comment by awolden** [comment]
Hey @Janking,

Unfortunately there is no drop in replacement for ribbon in node, but you can use a library like https://www.npmjs.com/package/resilient. And then use this eureka client to supply the resilient client with a list of servers (https://www.npmjs.com/package/resilient#discovery).

Hopefully that information helps!

-Alex

**Comment by Janking** [comment]
@awolden Thank you very much !
