### ISSUE TITLE
NodeJS Application unable to access from Zuul API Gateway

### ISSUE THREAD

**Issue by dileepkeeppalli** [jquatier/eureka-js-client#129]
Hi @jquatier, 

Created a NodeJS(Using ExpressJS) micro-service and registered it with Eureka Discovery Server using eureka-js-client (https://www.npmjs.com/package/eureka-js-client).

I already have some Java based micro-services registered with Eureka and using it through Zuul API Gateway.

When I try to invoke a specific end point on my NodeJS micro-service via API Gateway, it throws error

Caused by: com.netflix.client.ClientException: Load balancer does not 
have available server for client: tryout
Note: tryout is the name of my demo service application.

![screen shot 2017-12-19 at 11 18 14 am](https://user-images.githubusercontent.com/13331639/34143606-8b8677e0-e4b3-11e7-9dfd-0176935580a9.png)

**Comment by jquatier** [comment]
Hey @dileepkeeppalli,

Looks like your node app successfully registered with Eureka, which is what this module is in charge of. I see your application is UP in Eureka too, which means heartbeats are working. In that case, I think your issue is a problem on the load balancer configuration side or possibly with your healthcheck URL. Feel free to post your configuration as more detail.

My advice would be to check that your API gateway has the correct vipAddress / app name in it's configuration (`tryout`, in this case). If your API gateway uses vipAddresses to identify the application, make sure you are registering with a vip address and that it's the same vip address the API Gateway expects. Perhaps check the registry and compare the values that your Java applications register with, and make sure your nodejs app registers with similar values. 

Closing this issue for now since the module is working correctly.
