### ISSUE TITLE
dns dependency not found for DnsClusterResolver.js

### ISSUE THREAD

**Issue by MichaelWMerritt** [jquatier/eureka-js-client#132]
I am trying to use this module for registering my app with my Eureka server.  It is an Angular app.  However, when I try to run the application is gives a compile failure due to dns dependency not found.  dns is required by DnsClusterResolver.js but I don't see where dns is a dependency.

**Comment by jquatier** [comment]
DNS is included in node.js, which is where this module should be instantiated. This module is typically used on the application server, so if there's a Node.js application serving up the page, it would make more sense to instantiate the eureka-client there, instead of in the code that runs in the web browser. Else, anyone loading up the web application would end up registering with Eureka. Hope this helps!
