### ISSUE TITLE
Abstract specific configuration eureka version configuration

### ISSUE THREAD

**Issue by mikhas-rock** [jquatier/eureka-js-client#141]
I wonder if the library could abstract the eureka version specific configuration so users doesn't have to care about setting attributes such as `{'$': port,'@enabled': 'true'}` or `'@class':'com.netflix...'`

Not sure if there is an API call we can do to identify Eureka API compatibility.

**Comment by jquatier** [comment]
Not really. Theres a good discussion on the API differences that I linked to in the readme. The changes occurred in a minor version rev of Eureka, and there's also been some differences in the Spring Cloud flavor of Eureka. I think the config today is nice because its flexible with any other future differences, but it would be hard to track all of those. Anyway, for now I've just been trying to keep up with it in the README.
