### ISSUE TITLE
Optionally allow auto-deregister on downtime.

### ISSUE THREAD

**Issue by kesne** [jquatier/eureka-js-client#23]
Should we listen for when the process is exiting and automatically fire out a de-register if we boot with a config option that tells us to? I think it could be useful.

**Comment by jquatier** [comment]
Should be able to call the new stop() method from #24. Should we add a listener in our module for the 'exit' event?

**Comment by kesne** [comment]
I'm thinking optionally yeah. By default, maybe not, but it could be a configuration option.

**Comment by kesne** [comment]
Okay so what if we do a `deregisterOnCrash` flag that is set to true by default, and then add process event listeners for `uncaughtException` and `beforeExit`, and check if the flag is true. If it is, call `stop`.

**Comment by daveedgarcia** [comment]
+1 @kesne

**Comment by jquatier** [comment]
It feels a little aggressive. The deregister is going to happen automatically when the heartbeats fail. Also it makes it so you would probably never see DOWN in Asgard like we do today, it would show N/A instead because the instance wouldn't be registered at all. The Eureka status page would also look fine because it wouldn't show anything is down, you would have to notice that there's all the sudden 9 healthy instances instead of 10 (instead of 9 healthy and 1 down). You kind of lose track of that instance.

There's other options like taking it out of service... But that's usually used to enable / disable traffic. I'm not sure if that's better.

**Comment by kesne** [comment]
At the very least we should call stop on beforeExit optionally, because those are times you intentionally kill the process, where `DOWN` is not a good descriptor. 

The main idea here is to notice the instances are down faster than the heartbeat can tell.

**Comment by jquatier** [comment]
Totally understand the idea. I think calling stop on beforeExit sounds good (and a config option to disable), because it's intentional.

For uncaught exceptions let's just let the heartbeats fail as normal. With node process managers that auto-restart, users already have options to bring their app back up quickly to minimize periods where instances are down and Eureka isn't aware yet. Also under the normal model, clients have retry logic in so that if the first instance doesn't respond, the next one get's tried, etc. They have to have this, because while the Eureka server may know an instance has deregistered or gone down, clients (like ours) may not have that in their local cached registry. Odds are, even if you deregister early the clients wont find out for another 60 seconds anyway. But, I like the idea of doing it on an intentional exit.

**Comment by noseglid** [comment]
I don't think this should be the responsibility of the eureka client. It provides a `stop` method which does all the necessary operations. Any consumer should preferrably close it gracefully before terminating.

In the event of a crash, Eureka correctly removes the service when heartbeats fail. Clients using the service must have circuit breakers built in (as theres no way to guarantee that we will *always* deregister - imagine a pulled TCP cable).

IMO this should be closed and the functionality should be implemented by consumers.

**Comment by jquatier** [comment]
I'm good with that. Thanks for providing your thoughts!
