### ISSUE TITLE
Add option to disable polling for instance info

### ISSUE THREAD

**Issue by majgis** [jquatier/eureka-js-client#30]
If your application only needs to register with eureka and doesn't need information on other instances, there is no option to disable polling to /eureka/v2/apps.

I propose allowing eureka.registryFetchInterval set to a value to allow disabling of polling.  

Would you accept a pull request?

What should getInstancesByAppId and getInstancesByVipAddress return?  Empty arrays?
What value should eureka.registryFetchInterval be set to disable polling?  The null value works with deepmerge, but would be a breaking change, how about "DO_NOT_FETCH"?

**Comment by jquatier** [comment]
I think to be more consistent with the Java client we should just have a fetchRegistry flag that defaults to `true`. So, modify the default-config.js and set it to true, and then users can optionally set their configurations to false. You shouldn't need to change the getInstances methods; those will just throw an error if an instance isn't found because the cache will be empty. Would gladly accept a PR, or I can also probably add this feature later this week when I get some time. Thanks!

**Comment by kesne** [comment]
One thing we could consider is changing the error message if `fetchRegistry` is set to false that way it's clear why the methods for accessing instances are throwing.

**Comment by majgis** [comment]
It is looking like I would get to a PR later rather than sooner, so it is
best that you add this feature.  It would be much appreciated, thank you!

**Comment by kesne** [comment]
Sure, I'll tackle this tonight

**Comment by jquatier** [comment]
Version 1.7.0 now has the `fetchRegistry` option.

**Comment by majgis** [comment]
Thank you!
