### ISSUE TITLE
If renewals fails with 404 we need to register again

### ISSUE THREAD

**Issue by mogensen** [jquatier/eureka-js-client#47]
Hi,

If the lease of the eureka-client somehow runs out, without the heartbeat reaching the Eureka server, we need to register the application again.
This is handled by the Eureka server by responding to the renewal request with the status code 404.

See the Netflix implementation to : https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L825

Best,
/Frederik Mogensen

**Comment by jquatier** [comment]
Good callout. This should be fairly easy to implement. We can just make `renew()` call `register()` on a 404. One thing we might want to do is move the `startHeartbeats()` and `startRegistryFetches()` calls out of `register()` and into `start()` so that we don't have double the intervals when this happens. Other than that, should be a small code change + adding a unit test.

**Comment by jquatier** [comment]
Fixed in #50. Available in [v2.4.0](https://www.npmjs.com/package/eureka-js-client). Thanks again to @mogensen and @xanderv87.
