### ISSUE TITLE
Proxy configuration and getinstances by status

### ISSUE THREAD

**Issue by talbe1992** [jquatier/eureka-js-client#48]
Hi!
First, great work!
I work in a big corporate which uses proxy. 
Maybe you can include in the default2 requester a configurable proxy, taken from the YML.

Also, by getting the instances, it will be nice to get only the UP services :)

Thanks!

**Comment by jquatier** [comment]
`request` will actually honor the `HTTP_PROXY` and `HTTPS_PROXY` environment variables if you set those.

`export HTTP_PROXY=http://some.proxy.com:8080`

Would that work for your use case? It seems like its probably only a problem for local development, so environment variables might work, and your configuration could stay the same. We could also make it configurable on the client itself since `request` has a proxy option.

As for filtering instances, that seems like a good feature to add. It looks like the Java client does that anyway, https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java#L407

**Comment by talbe1992** [comment]
Hi.
For my case it will be necessary to configure the proxy. because I use my corporate local network and also I use internet services via proxy. So it will be nice to have proxy config.

As for the filtering, it will be good to have.

Thanks!

**Comment by jquatier** [comment]
Cool, I'll take a look when I get some time.

**Comment by jquatier** [comment]
@talbe1992 We release 3.0.0 today which filters UP instances by default.

As for the proxy configuration stuff, we decided to not instrument the code with proxy config. We looked at how this is handled in various other modules and usually users just pass in variables for `request` when they start their app. This allows the proxy setting to only affect the node process, which was your concern above. So you would do `HTTP_PROXY=http://some.proxy.com:8080 node app.js`. If you are using a process manager like [PM2](http://pm2.keymetrics.io/docs/usage/application-declaration/) this is even easier because you can configure the process manager to start your application always with the proxy set (or just for development). 

Anyway, hope this helps! I'll close this issue for now.
