### ISSUE TITLE
Do you have plan to support Http on vipAddress?

### ISSUE THREAD

**Issue by zhudan** [jquatier/eureka-js-client#90]
Do you have plan to support Http on vipAddress ? Call http interface between micro services。

**Comment by jquatier** [comment]
I think what you are describing is similar to Ribbon, which is what Netflix uses for communicating between services. (https://github.com/Netflix/ribbon). This module is designed to be purely a Eureka client for registration and fetching the registry. Once the registry is fetched you can make requests to those instances using a variety of HTTP clients. You'll also have to decide what strategy to use when load balancing to the instances. You could randomly pick an instance, or use a weighted or round-robin strategy. The default Ribbon implementation is round robin. I think most users of this module are using their own logic for this, since it allows you to choose what HTTP request library to use as well as what balancing strategy.

Anyway, hope this answers your question. If you do end up building a load balanced HTTP client (similar to Ribbon), it would make a great module on NPM. I think there's probably other users searching for the same thing.

**Comment by zhudan** [comment]
@jquatier ok,3qu,

recommend： https://github.com/resilient-http/resilient.js
