### ISSUE TITLE
Calling from outside of React works, but not from within React

### ISSUE THREAD

**Issue by cmitchell** [jquatier/eureka-js-client#96]
Forgive me if this isn't a true bug, but is more my ignorance. I'm really a java/golang dev, and my js kung fu is weak. I am using spring cloud. I have a scenario where I am SUCCESSFULLY able to connect to the eureka registry, but that connection happens at webpack time and I need it to be at load time.

So, I have a reducers/eureka.js with the following  (which works in the first scenario just fine)
```
const Eureka = require('eureka-js-client').Eureka;

const eurekaClient = new Eureka({
  instance: {
    app: 'test',
    hostName: 'localhost',
    ipAddr: '127.0.0.1',
    statusPageUrl: 'http://localhost:5000/info',
    healthCheckUrl: 'http://localhost:5000/health',
    port: {
      '$': 5000,
      '@enabled': 'true',
    },
    vipAddress: '127.0.0.1',
    dataCenterInfo: {
      '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
      name: 'MyOwn',
    },
  },
  eureka: {
    host: 'localhost',
    port: 8761,
    servicePath: '/eureka/apps/',
    requestRetryDelay: 3000,
    maxRetries: 10
  },
});
eurekaClient.logger.level('debug');

export default function connectToEureka() {
  eurekaClient.logger.level('debug');
  eurekaClient.start(function(error) {
    console.log('########################################################');
    console.log(error || 'Eureka registration complete');
  });
}
```

If I put the following in my reducers/simple.js
```
import connectToEureka from 'reducers/eureka';
connectToEureka();
```
I see at webpack time on the console, i.e. I have not hit the page.  Tests have run
```
  components
    ListComponent
      ✓ should render three items
registered with eureka:  test/localhost
      ✓ should fetch items on click
retrieved registry successfully
########################################################
Eureka registration complete
```
and on the server I see
```
discovery_1     | 2016-11-08 20:03:29.721  INFO 1 --- [nio-8761-exec-9] c.n.e.registry.AbstractInstanceRegistry  : Registered instance TEST/localhost with status UP (replication=false)
discovery_1     | 2016-11-08 20:03:30.233  INFO 1 --- [nio-8761-exec-3] c.n.e.registry.AbstractInstanceRegistry  : Registered instance TEST/localhost with status UP (replication=true)
```

Great!  So now I take that code out of reducers/simple.js and put code in my ui/containers/App.js so that it tries to register with Eureka at load time, instead of webpack.  The part of my App.js
```
import connectToEureka from 'reducers/eureka';
......
......
export class App extends Component {

 componentWillMount() {
    connectToEureka();
 }
```
and now I see nothing at webpack time 9which is expected), and when I load the page in the browser, on the server I see 
```
discovery_1     | 2016-11-08 19:56:29.363  INFO 1 --- [nio-8761-exec-3] .g.AbstractWadlGeneratorGrammarGenerator : Couldn't find grammar element for class javax.ws.rs.core.Response.  
```
I'm calling the same code (connectToEureka) in both cases. I've registered java and golang services with this instance of Eureka, so I doubt it's the server. Like I said, it is quite possible it's my weak js skills.  Has anyone else run into this issue?  Any help would be appreciated.

**Comment by cmitchell** [comment]
Actually, taking react out of the picture, so just doing this in my index.js

```
document.onLoad(connectToEureka());
```

Also gives the same issue. I know it says "INFO", but I'm pretty sure it's an error. The app doesn't register when that "INFO" message is output, and it does when it's not.

**Comment by jquatier** [comment]
Hey @cmitchell, Thanks for the details. 

I haven't heard of anyone registering a client-side React app in Eureka, because it's not an application server. It's just running in a web browser, correct? Eureka is typically used as a registry for application server instances (in AWS or other data centers). Since registering with Eureka is really only important when you want other servers to be able to "discover" your instance, I'm not sure what the benefit of having a React app register with Eureka is. Also, every user that ends up loading the React app in their browser would end up registering with Eureka too. 

Anyway, this module is typically used on the application server, so if there's a Node.js application serving up the page, it would make more sense to instantiate the eureka-client there, instead of in the code that runs in the web browser. This module uses a lot of dependencies that Webpack would probably have to bundle and transpile for the browser, so I'm not really sure what the results of that compilation process would be. My guess would be a _very_ large JS bundle, I'm not even sure if it would work because I haven't heard of anyone doing it. Definitely new territory for us. Let me know if I've made any incorrect assumptions!

**Comment by cmitchell** [comment]
Hi,

  Thanks, I just realized that I just need the UI to his the restful endoints of Eureka to discover the location of the services it needs, and that i don't need to register to do that.  Sorry for the confusion.
